
name: Build NFCApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Verify APK existence
        run: ls -l app/build/outputs/apk/debug/

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
