name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Verify APK existence
      run: ls -l app/build/outputs/apk/debug/

    - name: Upload APK
      uses: actions/upload-artifact@v4.6.2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
        retention-days: 7
        compression-level: 6
        overwrite: true
        include-hidden-files: false
